/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.khronos.collada.FuncType1;
import org.khronos.collada.ValueType;

/**
 * A sample validator interface for {@link org.khronos.collada.AlphaFuncType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AlphaFuncTypeValidator {
	boolean validate();

	boolean validateFunc(FuncType1 value);
	boolean validateValue(ValueType value);
}
