/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.khronos.collada.FuncType3;
import org.khronos.collada.ValueType1;

/**
 * A sample validator interface for {@link org.khronos.collada.AlphaFuncType1}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AlphaFuncType1Validator {
	boolean validate();

	boolean validateFunc(FuncType3 value);
	boolean validateValue(ValueType1 value);
}
