/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.eclipse.emf.common.util.EList;

import org.khronos.collada.AnimationType;
import org.khronos.collada.AssetType;
import org.khronos.collada.ChannelType;
import org.khronos.collada.ExtraType;
import org.khronos.collada.SamplerType;
import org.khronos.collada.SourceType;

/**
 * A sample validator interface for {@link org.khronos.collada.AnimationType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AnimationTypeValidator {
	boolean validate();

	boolean validateAsset(AssetType value);
	boolean validateSource(EList<SourceType> value);
	boolean validateSampler(EList<SamplerType> value);
	boolean validateChannel(EList<ChannelType> value);
	boolean validateAnimation(EList<AnimationType> value);
	boolean validateAnimation1(EList<AnimationType> value);
	boolean validateSampler1(EList<SamplerType> value);
	boolean validateChannel1(EList<ChannelType> value);
	boolean validateAnimation2(EList<AnimationType> value);
	boolean validateAnimation3(EList<AnimationType> value);
	boolean validateExtra(EList<ExtraType> value);
	boolean validateId(String value);
	boolean validateName(String value);
}
