/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import javax.xml.datatype.XMLGregorianCalendar;

import org.eclipse.emf.common.util.EList;

import org.khronos.collada.ContributorType;
import org.khronos.collada.UnitType;
import org.khronos.collada.UpAxisType;

/**
 * A sample validator interface for {@link org.khronos.collada.AssetType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AssetTypeValidator {
	boolean validate();

	boolean validateContributor(EList<ContributorType> value);
	boolean validateCreated(XMLGregorianCalendar value);
	boolean validateKeywords(String value);
	boolean validateModified(XMLGregorianCalendar value);
	boolean validateRevision(String value);
	boolean validateSubject(String value);
	boolean validateTitle(String value);
	boolean validateUnit(UnitType value);
	boolean validateUpAxis(UpAxisType value);
}
