/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

import org.khronos.collada.GlSampler1D;
import org.khronos.collada.GlSampler2D;
import org.khronos.collada.GlSampler3D;
import org.khronos.collada.GlSamplerCUBE;
import org.khronos.collada.GlSamplerDEPTH;
import org.khronos.collada.GlSamplerRECT;
import org.khronos.collada.GlslSurfaceType;
import org.khronos.collada.ParamType1;

/**
 * A sample validator interface for {@link org.khronos.collada.BindType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BindTypeValidator {
	boolean validate();

	boolean validateBool(boolean value);
	boolean validateBool2(List<Boolean> value);
	boolean validateBool3(List<Boolean> value);
	boolean validateBool4(List<Boolean> value);
	boolean validateFloat(float value);
	boolean validateFloat2(List<Float> value);
	boolean validateFloat3(List<Float> value);
	boolean validateFloat4(List<Float> value);
	boolean validateFloat2x2(List<Float> value);
	boolean validateFloat3x3(List<Float> value);
	boolean validateFloat4x4(List<Float> value);
	boolean validateInt(int value);
	boolean validateInt2(List<Integer> value);
	boolean validateInt3(List<Integer> value);
	boolean validateInt4(List<Integer> value);
	boolean validateSurface(GlslSurfaceType value);
	boolean validateSampler1D(GlSampler1D value);
	boolean validateSampler2D(GlSampler2D value);
	boolean validateSampler3D(GlSampler3D value);
	boolean validateSamplerCUBE(GlSamplerCUBE value);
	boolean validateSamplerRECT(GlSamplerRECT value);
	boolean validateSamplerDEPTH(GlSamplerDEPTH value);
	boolean validateEnum(Enumerator value);
	boolean validateParam(ParamType1 value);
	boolean validateSymbol(String value);
}
