/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.khronos.collada.DestAlphaType;
import org.khronos.collada.DestRgbType;
import org.khronos.collada.SrcAlphaType;
import org.khronos.collada.SrcRgbType;

/**
 * A sample validator interface for {@link org.khronos.collada.BlendFuncSeparateType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BlendFuncSeparateTypeValidator {
	boolean validate();

	boolean validateSrcRgb(SrcRgbType value);
	boolean validateDestRgb(DestRgbType value);
	boolean validateSrcAlpha(SrcAlphaType value);
	boolean validateDestAlpha(DestAlphaType value);
}
