/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.khronos.collada.DestType1;
import org.khronos.collada.SrcType1;

/**
 * A sample validator interface for {@link org.khronos.collada.BlendFuncType1}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BlendFuncType1Validator {
	boolean validate();

	boolean validateSrc(SrcType1 value);
	boolean validateDest(DestType1 value);
}
