/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

import org.khronos.collada.CgConnectParam;
import org.khronos.collada.CgSampler1D;
import org.khronos.collada.CgSampler2D;
import org.khronos.collada.CgSampler3D;
import org.khronos.collada.CgSamplerCUBE;
import org.khronos.collada.CgSamplerDEPTH;
import org.khronos.collada.CgSamplerRECT;
import org.khronos.collada.CgSetarrayType;
import org.khronos.collada.CgSetuserType;
import org.khronos.collada.CgSurfaceType;

/**
 * A sample validator interface for {@link org.khronos.collada.CgSetparam}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CgSetparamValidator {
	boolean validate();

	boolean validateBool(boolean value);
	boolean validateBool1(boolean value);
	boolean validateBool2(List<Boolean> value);
	boolean validateBool3(List<Boolean> value);
	boolean validateBool4(List<Boolean> value);
	boolean validateBool1x1(List<Boolean> value);
	boolean validateBool1x2(List<Boolean> value);
	boolean validateBool1x3(List<Boolean> value);
	boolean validateBool1x4(List<Boolean> value);
	boolean validateBool2x1(List<Boolean> value);
	boolean validateBool2x2(List<Boolean> value);
	boolean validateBool2x3(List<Boolean> value);
	boolean validateBool2x4(List<Boolean> value);
	boolean validateBool3x1(List<Boolean> value);
	boolean validateBool3x2(List<Boolean> value);
	boolean validateBool3x3(List<Boolean> value);
	boolean validateBool3x4(List<Boolean> value);
	boolean validateBool4x1(List<Boolean> value);
	boolean validateBool4x2(List<Boolean> value);
	boolean validateBool4x3(List<Boolean> value);
	boolean validateBool4x4(List<Boolean> value);
	boolean validateFloat(float value);
	boolean validateFloat1(float value);
	boolean validateFloat2(List<Float> value);
	boolean validateFloat3(List<Float> value);
	boolean validateFloat4(List<Float> value);
	boolean validateFloat1x1(List<Float> value);
	boolean validateFloat1x2(List<Float> value);
	boolean validateFloat1x3(List<Float> value);
	boolean validateFloat1x4(List<Float> value);
	boolean validateFloat2x1(List<Float> value);
	boolean validateFloat2x2(List<Float> value);
	boolean validateFloat2x3(List<Float> value);
	boolean validateFloat2x4(List<Float> value);
	boolean validateFloat3x1(List<Float> value);
	boolean validateFloat3x2(List<Float> value);
	boolean validateFloat3x3(List<Float> value);
	boolean validateFloat3x4(List<Float> value);
	boolean validateFloat4x1(List<Float> value);
	boolean validateFloat4x2(List<Float> value);
	boolean validateFloat4x3(List<Float> value);
	boolean validateFloat4x4(List<Float> value);
	boolean validateInt(int value);
	boolean validateInt1(int value);
	boolean validateInt2(List<Integer> value);
	boolean validateInt3(List<Integer> value);
	boolean validateInt4(List<Integer> value);
	boolean validateInt1x1(List<Integer> value);
	boolean validateInt1x2(List<Integer> value);
	boolean validateInt1x3(List<Integer> value);
	boolean validateInt1x4(List<Integer> value);
	boolean validateInt2x1(List<Integer> value);
	boolean validateInt2x2(List<Integer> value);
	boolean validateInt2x3(List<Integer> value);
	boolean validateInt2x4(List<Integer> value);
	boolean validateInt3x1(List<Integer> value);
	boolean validateInt3x2(List<Integer> value);
	boolean validateInt3x3(List<Integer> value);
	boolean validateInt3x4(List<Integer> value);
	boolean validateInt4x1(List<Integer> value);
	boolean validateInt4x2(List<Integer> value);
	boolean validateInt4x3(List<Integer> value);
	boolean validateInt4x4(List<Integer> value);
	boolean validateHalf(float value);
	boolean validateHalf1(float value);
	boolean validateHalf2(List<Float> value);
	boolean validateHalf3(List<Float> value);
	boolean validateHalf4(List<Float> value);
	boolean validateHalf1x1(List<Float> value);
	boolean validateHalf1x2(List<Float> value);
	boolean validateHalf1x3(List<Float> value);
	boolean validateHalf1x4(List<Float> value);
	boolean validateHalf2x1(List<Float> value);
	boolean validateHalf2x2(List<Float> value);
	boolean validateHalf2x3(List<Float> value);
	boolean validateHalf2x4(List<Float> value);
	boolean validateHalf3x1(List<Float> value);
	boolean validateHalf3x2(List<Float> value);
	boolean validateHalf3x3(List<Float> value);
	boolean validateHalf3x4(List<Float> value);
	boolean validateHalf4x1(List<Float> value);
	boolean validateHalf4x2(List<Float> value);
	boolean validateHalf4x3(List<Float> value);
	boolean validateHalf4x4(List<Float> value);
	boolean validateFixed(float value);
	boolean validateFixed1(float value);
	boolean validateFixed2(List<Float> value);
	boolean validateFixed3(List<Float> value);
	boolean validateFixed4(List<Float> value);
	boolean validateFixed1x1(List<Float> value);
	boolean validateFixed1x2(List<Float> value);
	boolean validateFixed1x3(List<Float> value);
	boolean validateFixed1x4(List<Float> value);
	boolean validateFixed2x1(List<Float> value);
	boolean validateFixed2x2(List<Float> value);
	boolean validateFixed2x3(List<Float> value);
	boolean validateFixed2x4(List<Float> value);
	boolean validateFixed3x1(List<Float> value);
	boolean validateFixed3x2(List<Float> value);
	boolean validateFixed3x3(List<Float> value);
	boolean validateFixed3x4(List<Float> value);
	boolean validateFixed4x1(List<Float> value);
	boolean validateFixed4x2(List<Float> value);
	boolean validateFixed4x3(List<Float> value);
	boolean validateFixed4x4(List<Float> value);
	boolean validateSurface(CgSurfaceType value);
	boolean validateSampler1D(CgSampler1D value);
	boolean validateSampler2D(CgSampler2D value);
	boolean validateSampler3D(CgSampler3D value);
	boolean validateSamplerRECT(CgSamplerRECT value);
	boolean validateSamplerCUBE(CgSamplerCUBE value);
	boolean validateSamplerDEPTH(CgSamplerDEPTH value);
	boolean validateString(String value);
	boolean validateEnum(Enumerator value);
	boolean validateUsertype(CgSetuserType value);
	boolean validateArray(CgSetarrayType value);
	boolean validateConnectParam(CgConnectParam value);
	boolean validateProgram(String value);
	boolean validateRef(String value);
}
