/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import java.util.List;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.Enumerator;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.khronos.collada.CgConnectParam;
import org.khronos.collada.CgSampler1D;
import org.khronos.collada.CgSampler2D;
import org.khronos.collada.CgSampler3D;
import org.khronos.collada.CgSamplerCUBE;
import org.khronos.collada.CgSamplerDEPTH;
import org.khronos.collada.CgSamplerRECT;
import org.khronos.collada.CgSetarrayType;
import org.khronos.collada.CgSetparam;
import org.khronos.collada.CgSetuserType;
import org.khronos.collada.CgSurfaceType;

/**
 * A sample validator interface for {@link org.khronos.collada.CgSetuserType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CgSetuserTypeValidator {
	boolean validate();

	boolean validateGroup(FeatureMap value);
	boolean validateBool(EList<Boolean> value);
	boolean validateBool1(EList<Boolean> value);
	boolean validateBool2(EList<List> value);
	boolean validateBool3(EList<List> value);
	boolean validateBool4(EList<List> value);
	boolean validateBool1x1(EList<List> value);
	boolean validateBool1x2(EList<List> value);
	boolean validateBool1x3(EList<List> value);
	boolean validateBool1x4(EList<List> value);
	boolean validateBool2x1(EList<List> value);
	boolean validateBool2x2(EList<List> value);
	boolean validateBool2x3(EList<List> value);
	boolean validateBool2x4(EList<List> value);
	boolean validateBool3x1(EList<List> value);
	boolean validateBool3x2(EList<List> value);
	boolean validateBool3x3(EList<List> value);
	boolean validateBool3x4(EList<List> value);
	boolean validateBool4x1(EList<List> value);
	boolean validateBool4x2(EList<List> value);
	boolean validateBool4x3(EList<List> value);
	boolean validateBool4x4(EList<List> value);
	boolean validateFloat(EList<Float> value);
	boolean validateFloat1(EList<Float> value);
	boolean validateFloat2(EList<List> value);
	boolean validateFloat3(EList<List> value);
	boolean validateFloat4(EList<List> value);
	boolean validateFloat1x1(EList<List> value);
	boolean validateFloat1x2(EList<List> value);
	boolean validateFloat1x3(EList<List> value);
	boolean validateFloat1x4(EList<List> value);
	boolean validateFloat2x1(EList<List> value);
	boolean validateFloat2x2(EList<List> value);
	boolean validateFloat2x3(EList<List> value);
	boolean validateFloat2x4(EList<List> value);
	boolean validateFloat3x1(EList<List> value);
	boolean validateFloat3x2(EList<List> value);
	boolean validateFloat3x3(EList<List> value);
	boolean validateFloat3x4(EList<List> value);
	boolean validateFloat4x1(EList<List> value);
	boolean validateFloat4x2(EList<List> value);
	boolean validateFloat4x3(EList<List> value);
	boolean validateFloat4x4(EList<List> value);
	boolean validateInt(EList<Integer> value);
	boolean validateInt1(EList<Integer> value);
	boolean validateInt2(EList<List> value);
	boolean validateInt3(EList<List> value);
	boolean validateInt4(EList<List> value);
	boolean validateInt1x1(EList<List> value);
	boolean validateInt1x2(EList<List> value);
	boolean validateInt1x3(EList<List> value);
	boolean validateInt1x4(EList<List> value);
	boolean validateInt2x1(EList<List> value);
	boolean validateInt2x2(EList<List> value);
	boolean validateInt2x3(EList<List> value);
	boolean validateInt2x4(EList<List> value);
	boolean validateInt3x1(EList<List> value);
	boolean validateInt3x2(EList<List> value);
	boolean validateInt3x3(EList<List> value);
	boolean validateInt3x4(EList<List> value);
	boolean validateInt4x1(EList<List> value);
	boolean validateInt4x2(EList<List> value);
	boolean validateInt4x3(EList<List> value);
	boolean validateInt4x4(EList<List> value);
	boolean validateHalf(EList<Float> value);
	boolean validateHalf1(EList<Float> value);
	boolean validateHalf2(EList<List> value);
	boolean validateHalf3(EList<List> value);
	boolean validateHalf4(EList<List> value);
	boolean validateHalf1x1(EList<List> value);
	boolean validateHalf1x2(EList<List> value);
	boolean validateHalf1x3(EList<List> value);
	boolean validateHalf1x4(EList<List> value);
	boolean validateHalf2x1(EList<List> value);
	boolean validateHalf2x2(EList<List> value);
	boolean validateHalf2x3(EList<List> value);
	boolean validateHalf2x4(EList<List> value);
	boolean validateHalf3x1(EList<List> value);
	boolean validateHalf3x2(EList<List> value);
	boolean validateHalf3x3(EList<List> value);
	boolean validateHalf3x4(EList<List> value);
	boolean validateHalf4x1(EList<List> value);
	boolean validateHalf4x2(EList<List> value);
	boolean validateHalf4x3(EList<List> value);
	boolean validateHalf4x4(EList<List> value);
	boolean validateFixed(EList<Float> value);
	boolean validateFixed1(EList<Float> value);
	boolean validateFixed2(EList<List> value);
	boolean validateFixed3(EList<List> value);
	boolean validateFixed4(EList<List> value);
	boolean validateFixed1x1(EList<List> value);
	boolean validateFixed1x2(EList<List> value);
	boolean validateFixed1x3(EList<List> value);
	boolean validateFixed1x4(EList<List> value);
	boolean validateFixed2x1(EList<List> value);
	boolean validateFixed2x2(EList<List> value);
	boolean validateFixed2x3(EList<List> value);
	boolean validateFixed2x4(EList<List> value);
	boolean validateFixed3x1(EList<List> value);
	boolean validateFixed3x2(EList<List> value);
	boolean validateFixed3x3(EList<List> value);
	boolean validateFixed3x4(EList<List> value);
	boolean validateFixed4x1(EList<List> value);
	boolean validateFixed4x2(EList<List> value);
	boolean validateFixed4x3(EList<List> value);
	boolean validateFixed4x4(EList<List> value);
	boolean validateSurface(EList<CgSurfaceType> value);
	boolean validateSampler1D(EList<CgSampler1D> value);
	boolean validateSampler2D(EList<CgSampler2D> value);
	boolean validateSampler3D(EList<CgSampler3D> value);
	boolean validateSamplerRECT(EList<CgSamplerRECT> value);
	boolean validateSamplerCUBE(EList<CgSamplerCUBE> value);
	boolean validateSamplerDEPTH(EList<CgSamplerDEPTH> value);
	boolean validateString(EList<String> value);
	boolean validateEnum(EList<Enumerator> value);
	boolean validateArray(EList<CgSetarrayType> value);
	boolean validateUsertype(EList<CgSetuserType> value);
	boolean validateConnectParam(EList<CgConnectParam> value);
	boolean validateSetparam(EList<CgSetparam> value);
	boolean validateName(String value);
	boolean validateSource(String value);
}
