/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.khronos.collada.ColorType;
import org.khronos.collada.ParamType;
import org.khronos.collada.TextureType;

/**
 * A sample validator interface for {@link org.khronos.collada.CommonColorOrTextureType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CommonColorOrTextureTypeValidator {
	boolean validate();

	boolean validateColor(ColorType value);
	boolean validateParam(ParamType value);
	boolean validateTexture(TextureType value);
}
