/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import java.util.List;

import org.khronos.collada.FxSampler2DCommon;
import org.khronos.collada.FxSurfaceCommon;

/**
 * A sample validator interface for {@link org.khronos.collada.CommonNewparamType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CommonNewparamTypeValidator {
	boolean validate();

	boolean validateSemantic(String value);
	boolean validateFloat(double value);
	boolean validateFloat2(List<Double> value);
	boolean validateFloat3(List<Double> value);
	boolean validateFloat4(List<Double> value);
	boolean validateSurface(FxSurfaceCommon value);
	boolean validateSampler2D(FxSampler2DCommon value);
	boolean validateSid(String value);
}
