/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.khronos.collada.CommonColorOrTextureType;
import org.khronos.collada.CommonFloatOrParamType;
import org.khronos.collada.CommonTransparentType;

/**
 * A sample validator interface for {@link org.khronos.collada.ConstantType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConstantTypeValidator {
	boolean validate();

	boolean validateEmission(CommonColorOrTextureType value);
	boolean validateReflective(CommonColorOrTextureType value);
	boolean validateReflectivity(CommonFloatOrParamType value);
	boolean validateTransparent(CommonTransparentType value);
	boolean validateTransparency(CommonFloatOrParamType value);
	boolean validateIndexOfRefraction(CommonFloatOrParamType value);
}
