/**
 *
 * $Id$
 */
package org.khronos.collada.validation;


/**
 * A sample validator interface for {@link org.khronos.collada.ContributorType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContributorTypeValidator {
	boolean validate();

	boolean validateAuthor(String value);
	boolean validateAuthoringTool(String value);
	boolean validateComments(String value);
	boolean validateCopyright(String value);
	boolean validateSourceData(String value);
}
