/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import java.util.List;

import org.eclipse.emf.common.util.EList;

import org.khronos.collada.ExtraType;

/**
 * A sample validator interface for {@link org.khronos.collada.CylinderType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CylinderTypeValidator {
	boolean validate();

	boolean validateHeight(double value);
	boolean validateRadius(List<Double> value);
	boolean validateExtra(EList<ExtraType> value);
}
