/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.khronos.collada.AssetType;
import org.khronos.collada.ExtraType;
import org.khronos.collada.FxAnnotateCommon;
import org.khronos.collada.FxNewparamCommon;
import org.khronos.collada.ImageType;

/**
 * A sample validator interface for {@link org.khronos.collada.EffectType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EffectTypeValidator {
	boolean validate();

	boolean validateAsset(AssetType value);
	boolean validateAnnotate(EList<FxAnnotateCommon> value);
	boolean validateImage(EList<ImageType> value);
	boolean validateNewparam(EList<FxNewparamCommon> value);
	boolean validateFxProfileAbstractGroup(FeatureMap value);
	boolean validateFxProfileAbstract(EList<EObject> value);
	boolean validateExtra(EList<ExtraType> value);
	boolean validateId(String value);
	boolean validateName(String value);
}
