/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import java.util.List;

/**
 * A sample validator interface for {@link org.khronos.collada.FxAnnotateCommon}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FxAnnotateCommonValidator {
	boolean validate();

	boolean validateBool(boolean value);
	boolean validateBool2(List<Boolean> value);
	boolean validateBool3(List<Boolean> value);
	boolean validateBool4(List<Boolean> value);
	boolean validateInt(long value);
	boolean validateInt2(List<Long> value);
	boolean validateInt3(List<Long> value);
	boolean validateInt4(List<Long> value);
	boolean validateFloat(double value);
	boolean validateFloat2(List<Double> value);
	boolean validateFloat3(List<Double> value);
	boolean validateFloat4(List<Double> value);
	boolean validateFloat2x2(List<Double> value);
	boolean validateFloat3x3(List<Double> value);
	boolean validateFloat4x4(List<Double> value);
	boolean validateString(String value);
	boolean validateName(String value);
}
