/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import java.math.BigInteger;

import org.khronos.collada.FxSurfaceFaceEnum;

/**
 * A sample validator interface for {@link org.khronos.collada.FxDepthtargetCommon}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FxDepthtargetCommonValidator {
	boolean validate();

	boolean validateValue(String value);
	boolean validateFace(FxSurfaceFaceEnum value);
	boolean validateIndex(BigInteger value);
	boolean validateMip(BigInteger value);
	boolean validateSlice(BigInteger value);
}
