/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.eclipse.emf.common.util.EList;

import org.khronos.collada.AllType2;
import org.khronos.collada.FaceType4;
import org.khronos.collada.PrimaryType1;

/**
 * A sample validator interface for {@link org.khronos.collada.FxSurfaceInitCubeCommon}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FxSurfaceInitCubeCommonValidator {
	boolean validate();

	boolean validateAll(AllType2 value);
	boolean validatePrimary(PrimaryType1 value);
	boolean validateFace(EList<FaceType4> value);
}
