/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import java.util.List;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.khronos.collada.ExtraType;
import org.khronos.collada.FxSurfaceFormatHintCommon;
import org.khronos.collada.FxSurfaceInitCubeCommon;
import org.khronos.collada.FxSurfaceInitFromCommon;
import org.khronos.collada.FxSurfaceInitPlanarCommon;
import org.khronos.collada.FxSurfaceInitVolumeCommon;
import org.khronos.collada.FxSurfaceTypeEnum;

/**
 * A sample validator interface for {@link org.khronos.collada.FxSurfaceCommon}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FxSurfaceCommonValidator {
	boolean validate();

	boolean validateInitAsNull(EObject value);
	boolean validateInitAsTarget(EObject value);
	boolean validateInitCube(FxSurfaceInitCubeCommon value);
	boolean validateInitVolume(FxSurfaceInitVolumeCommon value);
	boolean validateInitPlanar(FxSurfaceInitPlanarCommon value);
	boolean validateInitFrom(EList<FxSurfaceInitFromCommon> value);
	boolean validateFormat(String value);
	boolean validateFormatHint(FxSurfaceFormatHintCommon value);
	boolean validateSize(List<Long> value);
	boolean validateViewportRatio(List<Double> value);
	boolean validateMipLevels(long value);
	boolean validateMipmapGenerate(boolean value);
	boolean validateExtra(EList<ExtraType> value);
	boolean validateType(FxSurfaceTypeEnum value);
}
