/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.eclipse.emf.common.util.EList;

import org.khronos.collada.ExtraType;
import org.khronos.collada.FxSurfaceFormatHintChannelsEnum;
import org.khronos.collada.FxSurfaceFormatHintOptionEnum;
import org.khronos.collada.FxSurfaceFormatHintPrecisionEnum;
import org.khronos.collada.FxSurfaceFormatHintRangeEnum;

/**
 * A sample validator interface for {@link org.khronos.collada.FxSurfaceFormatHintCommon}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FxSurfaceFormatHintCommonValidator {
	boolean validate();

	boolean validateChannels(FxSurfaceFormatHintChannelsEnum value);
	boolean validateRange(FxSurfaceFormatHintRangeEnum value);
	boolean validatePrecision(FxSurfaceFormatHintPrecisionEnum value);
	boolean validateOption(EList<FxSurfaceFormatHintOptionEnum> value);
	boolean validateExtra(EList<ExtraType> value);
}
