/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.khronos.collada.FxAnnotateCommon;
import org.khronos.collada.FxCodeProfile;
import org.khronos.collada.FxIncludeCommon;
import org.khronos.collada.GlslSetparamSimple;
import org.khronos.collada.NameType2;

/**
 * A sample validator interface for {@link org.khronos.collada.GeneratorType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GeneratorTypeValidator {
	boolean validate();

	boolean validateAnnotate(EList<FxAnnotateCommon> value);
	boolean validateGroup(FeatureMap value);
	boolean validateCode(EList<FxCodeProfile> value);
	boolean validateInclude(EList<FxIncludeCommon> value);
	boolean validateName(NameType2 value);
	boolean validateSetparam(EList<GlslSetparamSimple> value);
}
