/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import java.util.List;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.Enumerator;

import org.khronos.collada.FxAnnotateCommon;
import org.khronos.collada.FxModifierEnumCommon;
import org.khronos.collada.FxSurfaceCommon;
import org.khronos.collada.GlesSamplerState;
import org.khronos.collada.GlesTexturePipeline;
import org.khronos.collada.GlesTextureUnit;

/**
 * A sample validator interface for {@link org.khronos.collada.GlesNewparam}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GlesNewparamValidator {
	boolean validate();

	boolean validateAnnotate(EList<FxAnnotateCommon> value);
	boolean validateSemantic(String value);
	boolean validateModifier(FxModifierEnumCommon value);
	boolean validateBool(boolean value);
	boolean validateBool2(List<Boolean> value);
	boolean validateBool3(List<Boolean> value);
	boolean validateBool4(List<Boolean> value);
	boolean validateInt(long value);
	boolean validateInt2(List<Long> value);
	boolean validateInt3(List<Long> value);
	boolean validateInt4(List<Long> value);
	boolean validateFloat(double value);
	boolean validateFloat2(List<Double> value);
	boolean validateFloat3(List<Double> value);
	boolean validateFloat4(List<Double> value);
	boolean validateFloat1x1(double value);
	boolean validateFloat1x2(List<Double> value);
	boolean validateFloat1x3(List<Double> value);
	boolean validateFloat1x4(List<Double> value);
	boolean validateFloat2x1(List<Double> value);
	boolean validateFloat2x2(List<Double> value);
	boolean validateFloat2x3(List<Double> value);
	boolean validateFloat2x4(List<Double> value);
	boolean validateFloat3x1(List<Double> value);
	boolean validateFloat3x2(List<Double> value);
	boolean validateFloat3x3(List<Double> value);
	boolean validateFloat3x4(List<Double> value);
	boolean validateFloat4x1(List<Double> value);
	boolean validateFloat4x2(List<Double> value);
	boolean validateFloat4x3(List<Double> value);
	boolean validateFloat4x4(List<Double> value);
	boolean validateSurface(FxSurfaceCommon value);
	boolean validateTexturePipeline(GlesTexturePipeline value);
	boolean validateSamplerState(GlesSamplerState value);
	boolean validateTextureUnit(GlesTextureUnit value);
	boolean validateEnum(Enumerator value);
	boolean validateSid(String value);
}
