/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.khronos.collada.GlesTexcombinerOperandAlphaEnums;
import org.khronos.collada.GlesTexcombinerSourceEnums;

/**
 * A sample validator interface for {@link org.khronos.collada.GlesTexcombinerArgumentAlphaType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GlesTexcombinerArgumentAlphaTypeValidator {
	boolean validate();

	boolean validateOperand(GlesTexcombinerOperandAlphaEnums value);
	boolean validateSource(GlesTexcombinerSourceEnums value);
	boolean validateUnit(String value);
}
