/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.eclipse.emf.common.util.EList;

import org.khronos.collada.ExtraType;
import org.khronos.collada.InstanceRigidBodyType;
import org.khronos.collada.InstanceRigidConstraintType;
import org.khronos.collada.InstanceWithExtra;

/**
 * A sample validator interface for {@link org.khronos.collada.InstancePhysicsModelType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InstancePhysicsModelTypeValidator {
	boolean validate();

	boolean validateInstanceForceField(EList<InstanceWithExtra> value);
	boolean validateInstanceRigidBody(EList<InstanceRigidBodyType> value);
	boolean validateInstanceRigidConstraint(EList<InstanceRigidConstraintType> value);
	boolean validateExtra(EList<ExtraType> value);
	boolean validateName(String value);
	boolean validateParent(String value);
	boolean validateSid(String value);
	boolean validateUrl(String value);
}
