/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.eclipse.emf.common.util.EList;

import org.khronos.collada.BindType2;
import org.khronos.collada.BindVertexInputType;
import org.khronos.collada.ExtraType;

/**
 * A sample validator interface for {@link org.khronos.collada.InstanceMaterialType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InstanceMaterialTypeValidator {
	boolean validate();

	boolean validateBind(EList<BindType2> value);
	boolean validateBindVertexInput(EList<BindVertexInputType> value);
	boolean validateExtra(EList<ExtraType> value);
	boolean validateName(String value);
	boolean validateSid(String value);
	boolean validateSymbol(String value);
	boolean validateTarget(String value);
}
