/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.eclipse.emf.common.util.EList;

import org.khronos.collada.ExtraType;
import org.khronos.collada.TechniqueCommonType6;
import org.khronos.collada.TechniqueType4;

/**
 * A sample validator interface for {@link org.khronos.collada.InstanceRigidBodyType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InstanceRigidBodyTypeValidator {
	boolean validate();

	boolean validateTechniqueCommon(TechniqueCommonType6 value);
	boolean validateTechnique(EList<TechniqueType4> value);
	boolean validateExtra(EList<ExtraType> value);
	boolean validateBody(String value);
	boolean validateName(String value);
	boolean validateSid(String value);
	boolean validateTarget(String value);
}
