/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.khronos.collada.TargetableFloat3;

/**
 * A sample validator interface for {@link org.khronos.collada.LinearType1}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LinearType1Validator {
	boolean validate();

	boolean validateMin(TargetableFloat3 value);
	boolean validateMax(TargetableFloat3 value);
}
