/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.eclipse.emf.common.util.EList;

import org.khronos.collada.ExtraType;
import org.khronos.collada.MorphMethodType;
import org.khronos.collada.SourceType;
import org.khronos.collada.TargetsType;

/**
 * A sample validator interface for {@link org.khronos.collada.MorphType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MorphTypeValidator {
	boolean validate();

	boolean validateSource(EList<SourceType> value);
	boolean validateTargets(TargetsType value);
	boolean validateExtra(EList<ExtraType> value);
	boolean validateMethod(MorphMethodType value);
	boolean validateSource1(String value);
}
