/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.eclipse.emf.common.util.EList;

import org.khronos.collada.ExtraType;
import org.khronos.collada.InstanceWithExtra;

/**
 * A sample validator interface for {@link org.khronos.collada.SceneType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SceneTypeValidator {
	boolean validate();

	boolean validateInstancePhysicsScene(EList<InstanceWithExtra> value);
	boolean validateInstanceVisualScene(InstanceWithExtra value);
	boolean validateExtra(EList<ExtraType> value);

	boolean validateName(String value);
}
