/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.eclipse.emf.common.util.EList;

import org.khronos.collada.BindType;
import org.khronos.collada.CompilerTargetType;
import org.khronos.collada.FxAnnotateCommon;
import org.khronos.collada.GlslPipelineStage;
import org.khronos.collada.NameType1;

/**
 * A sample validator interface for {@link org.khronos.collada.ShaderType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ShaderTypeValidator {
	boolean validate();

	boolean validateAnnotate(EList<FxAnnotateCommon> value);
	boolean validateCompilerTarget(CompilerTargetType value);
	boolean validateCompilerOptions(String value);
	boolean validateName(NameType1 value);
	boolean validateBind(EList<BindType> value);
	boolean validateStage(GlslPipelineStage value);
}
