/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.eclipse.emf.common.util.EList;

import org.khronos.collada.BindType1;
import org.khronos.collada.CgPipelineStage;
import org.khronos.collada.CompilerTargetType1;
import org.khronos.collada.FxAnnotateCommon;
import org.khronos.collada.NameType;

/**
 * A sample validator interface for {@link org.khronos.collada.ShaderType1}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ShaderType1Validator {
	boolean validate();

	boolean validateAnnotate(EList<FxAnnotateCommon> value);
	boolean validateCompilerTarget(CompilerTargetType1 value);
	boolean validateCompilerOptions(String value);
	boolean validateName(NameType value);
	boolean validateBind(EList<BindType1> value);
	boolean validateStage(CgPipelineStage value);
}
