/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.eclipse.emf.common.util.EList;

import org.khronos.collada.AssetType;
import org.khronos.collada.BoolArrayType;
import org.khronos.collada.FloatArrayType;
import org.khronos.collada.IDREFArrayType;
import org.khronos.collada.IntArrayType;
import org.khronos.collada.NameArrayType;
import org.khronos.collada.TechniqueCommonType8;
import org.khronos.collada.TechniqueType4;

/**
 * A sample validator interface for {@link org.khronos.collada.SourceType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SourceTypeValidator {
	boolean validate();

	boolean validateAsset(AssetType value);
	boolean validateIDREFArray(IDREFArrayType value);
	boolean validateNameArray(NameArrayType value);
	boolean validateBoolArray(BoolArrayType value);
	boolean validateFloatArray(FloatArrayType value);
	boolean validateIntArray(IntArrayType value);
	boolean validateTechniqueCommon(TechniqueCommonType8 value);
	boolean validateTechnique(EList<TechniqueType4> value);
	boolean validateId(String value);
	boolean validateName(String value);
}
