/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.khronos.collada.AngularType;
import org.khronos.collada.LinearType;

/**
 * A sample validator interface for {@link org.khronos.collada.SpringType1}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SpringType1Validator {
	boolean validate();

	boolean validateAngular(AngularType value);
	boolean validateLinear(LinearType value);
}
