/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.khronos.collada.BackType;
import org.khronos.collada.FrontType;
import org.khronos.collada.MaskType2;
import org.khronos.collada.RefType;

/**
 * A sample validator interface for {@link org.khronos.collada.StencilFuncSeparateType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StencilFuncSeparateTypeValidator {
	boolean validate();

	boolean validateFront(FrontType value);
	boolean validateBack(BackType value);
	boolean validateRef(RefType value);
	boolean validateMask(MaskType2 value);
}
