/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.khronos.collada.FaceType2;
import org.khronos.collada.MaskType;

/**
 * A sample validator interface for {@link org.khronos.collada.StencilMaskSeparateType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StencilMaskSeparateTypeValidator {
	boolean validate();

	boolean validateFace(FaceType2 value);
	boolean validateMask(MaskType value);
}
