/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.khronos.collada.FuncType2;
import org.khronos.collada.MaskType3;
import org.khronos.collada.RefType2;

/**
 * A sample validator interface for {@link org.khronos.collada.StencilFuncType1}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StencilFuncType1Validator {
	boolean validate();

	boolean validateFunc(FuncType2 value);
	boolean validateRef(RefType2 value);
	boolean validateMask(MaskType3 value);
}
