/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.khronos.collada.FailType;
import org.khronos.collada.ZfailType1;
import org.khronos.collada.ZpassType;

/**
 * A sample validator interface for {@link org.khronos.collada.StencilOpType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StencilOpTypeValidator {
	boolean validate();

	boolean validateFail(FailType value);
	boolean validateZfail(ZfailType1 value);
	boolean validateZpass(ZpassType value);
}
