/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.khronos.collada.AmbientType;
import org.khronos.collada.DirectionalType;
import org.khronos.collada.PointType;
import org.khronos.collada.SpotType;

/**
 * A sample validator interface for {@link org.khronos.collada.TechniqueCommonType3}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TechniqueCommonType3Validator {
	boolean validate();

	boolean validateAmbient(AmbientType value);
	boolean validateDirectional(DirectionalType value);
	boolean validatePoint(PointType value);
	boolean validateSpot(SpotType value);
}
