/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.khronos.collada.AssetType;
import org.khronos.collada.ExtraType;
import org.khronos.collada.FxAnnotateCommon;
import org.khronos.collada.GlesNewparam;
import org.khronos.collada.ImageType;
import org.khronos.collada.PassType;
import org.khronos.collada.SetparamType;

/**
 * A sample validator interface for {@link org.khronos.collada.TechniqueType1}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TechniqueType1Validator {
	boolean validate();

	boolean validateAsset(AssetType value);
	boolean validateAnnotate(EList<FxAnnotateCommon> value);
	boolean validateGroup(FeatureMap value);
	boolean validateImage(EList<ImageType> value);
	boolean validateNewparam(EList<GlesNewparam> value);
	boolean validateSetparam(EList<SetparamType> value);
	boolean validatePass(EList<PassType> value);
	boolean validateExtra(EList<ExtraType> value);
	boolean validateId(String value);
	boolean validateSid(String value);
}
