/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.eclipse.emf.common.util.EList;

import org.khronos.collada.DynamicType1;
import org.khronos.collada.InstanceWithExtra;
import org.khronos.collada.MassFrameType1;
import org.khronos.collada.PhysicsMaterialType;
import org.khronos.collada.ShapeType1;
import org.khronos.collada.TargetableFloat;
import org.khronos.collada.TargetableFloat3;

/**
 * A sample validator interface for {@link org.khronos.collada.TechniqueCommonType1}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TechniqueCommonType1Validator {
	boolean validate();

	boolean validateDynamic(DynamicType1 value);
	boolean validateMass(TargetableFloat value);
	boolean validateMassFrame(MassFrameType1 value);
	boolean validateInertia(TargetableFloat3 value);
	boolean validateInstancePhysicsMaterial(InstanceWithExtra value);
	boolean validatePhysicsMaterial(PhysicsMaterialType value);
	boolean validateShape(EList<ShapeType1> value);
}
