/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.khronos.collada.AssetType;
import org.khronos.collada.CgNewparam;
import org.khronos.collada.CgSetparam;
import org.khronos.collada.ExtraType;
import org.khronos.collada.FxAnnotateCommon;
import org.khronos.collada.FxCodeProfile;
import org.khronos.collada.FxIncludeCommon;
import org.khronos.collada.ImageType;
import org.khronos.collada.PassType2;

/**
 * A sample validator interface for {@link org.khronos.collada.TechniqueType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TechniqueTypeValidator {
	boolean validate();

	boolean validateAsset(AssetType value);
	boolean validateAnnotate(EList<FxAnnotateCommon> value);
	boolean validateGroup(FeatureMap value);
	boolean validateCode(EList<FxCodeProfile> value);
	boolean validateInclude(EList<FxIncludeCommon> value);
	boolean validateGroup1(FeatureMap value);
	boolean validateImage(EList<ImageType> value);
	boolean validateNewparam(EList<CgNewparam> value);
	boolean validateSetparam(EList<CgSetparam> value);
	boolean validatePass(EList<PassType2> value);
	boolean validateExtra(EList<ExtraType> value);
	boolean validateId(String value);
	boolean validateSid(String value);
}
