/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.khronos.collada.TargetableFloat;

/**
 * A sample validator interface for {@link org.khronos.collada.TechniqueCommonType4}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TechniqueCommonType4Validator {
	boolean validate();

	boolean validateDynamicFriction(TargetableFloat value);
	boolean validateRestitution(TargetableFloat value);
	boolean validateStaticFriction(TargetableFloat value);
}
