/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import java.util.List;

import org.eclipse.emf.common.util.EList;

import org.khronos.collada.DynamicType;
import org.khronos.collada.InstanceWithExtra;
import org.khronos.collada.MassFrameType;
import org.khronos.collada.PhysicsMaterialType;
import org.khronos.collada.ShapeType;
import org.khronos.collada.TargetableFloat;
import org.khronos.collada.TargetableFloat3;

/**
 * A sample validator interface for {@link org.khronos.collada.TechniqueCommonType6}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TechniqueCommonType6Validator {
	boolean validate();

	boolean validateAngularVelocity(List<Double> value);
	boolean validateVelocity(List<Double> value);
	boolean validateDynamic(DynamicType value);
	boolean validateMass(TargetableFloat value);
	boolean validateMassFrame(MassFrameType value);
	boolean validateInertia(TargetableFloat3 value);
	boolean validateInstancePhysicsMaterial(InstanceWithExtra value);
	boolean validatePhysicsMaterial(PhysicsMaterialType value);
	boolean validateShape(EList<ShapeType> value);
}
