/**
 *
 * $Id$
 */
package org.khronos.collada.validation;

import org.khronos.collada.TargetableFloat;
import org.khronos.collada.TargetableFloat3;

/**
 * A sample validator interface for {@link org.khronos.collada.TechniqueCommonType7}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TechniqueCommonType7Validator {
	boolean validate();

	boolean validateGravity(TargetableFloat3 value);
	boolean validateTimeStep(TargetableFloat value);
}
